### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by dragenx** [phpBB-Blog/phpBB-Blog#27] opened 2012-01-03 17:49 UTC
Try to installed to mod got a database error also the UMIL files showing to be outdated on the mod. The version my site is running is phpbb 3.0.10 also I had to download the UMIL file which is version 1.0.4 from here http://www.phpbb.com/mods/umil/

I uninstalled the blog till there is a fixs for it

Inserting data in the phpbb_1blog_categories database table.

ERROR: Database table phpbb_1blog_categories does not exist.

**Comment by michaelcullum** [comment] 2012-01-03 17:53
Did you use the umil included in the package or UMIL 1.0.4?

**Comment by dragenx** [comment] 2012-01-03 18:03
I try is with the one in the package got the same error so I try it with the 1.0.4 still same error. Went I click on the install file got a box said that the UMIL was out of date

**Comment by michaelcullum** [comment] 2012-01-03 18:14
hm... I'm not able to reproduce this (except updating UMIL which I've done locally). I'll be releasing 1.0.0 in a couple of days, if you still get it with that then I'll keep this open, if not I'll close it.

**Comment by michaelcullum** [comment] 2012-01-03 18:14
Which page is this error on?

**Comment by dragenx** [comment] 2012-01-03 18:24
Getting it on the last page Action This is what I see now on the page

phpBB Blog - Fail

Database type :: mysql4

Warning
One or more errors occured during the requested action. Please download this file with the errors listed in it and ask the mod author for assistance.

If you have any problem downloading that file you may access it directly with an FTP browser at the following location: umil/error_files/phpbb blog5.txt

Warning
New permission settings have been added. Be sure to check your permission settings and see that they are as you would like them.

Adding a new database table: phpbb_1blog

SQL ERROR Table 'phpbb_1blog' already exists

---

Adding a new database table: phpbb_1blog_comments

SQL ERROR Table 'phpbb_1blog_comments' already exists

---

Adding a new database table: phpbb_1blog_categories

SQL ERROR Table 'phpbb_1blog_categories' already exists

---

Inserting data in the phpbb_1blog_categories database table.

ERROR: Database table phpbb_1blog_categories does not exist.

**Comment by michaelcullum** [comment] 2012-01-03 18:29
I'll review this after the hopeful release on friday.

**Comment by dragenx** [comment] 2012-01-03 18:31
went I looked at the blog on my site got this on the page

Warning: Call-time pass-by-reference has been deprecated in D:\hosting\7757950\html\includes\mods\functions_blog.php on line 158

**Comment by michaelcullum** [comment] 2012-01-03 18:34
Could you make a seperate bug report for that please? Thanks

**Comment by dragenx** [comment] 2012-01-03 18:35
another one for you got this on the blog overview in red box 

The update server appears to be down. Try again in a few minutes. If the problem persists for more than a day, please check the development topic at phpBB.com for the latest version information. - Update to

**Comment by michaelcullum** [comment] 2012-01-03 19:00
I am aware of that. Its on a different server now but the update will only become available in the new release.

**Comment by michaelcullum** [comment] 2012-01-03 22:18
I'm going to close this as fixed. If it still doesn't work in 1.0.0 which will be released shortly then feel free to re-open it.

**Closed as completed by michaelcullum** 2012-01-03 22:18 UTC
Labels: Bug, Unreproducible
