### ISSUE TITLE
Warning on blog

### ISSUE THREAD

**Issue by dragenx** [phpBB-Blog/phpBB-Blog#30] opened 2012-01-03 18:50 UTC
went I looked at the blog on my site got this on the page

Warning: Call-time pass-by-reference has been deprecated in D:\hosting\7757950\html\includes\mods\functions_blog.php on line 158

Line 158

```
$s = submit_post('post', $subject, $user->data['username'], POST_NORMAL, &$poll, &$data);  
```

**Comment by michaelcullum** [comment] 2012-01-04 01:43
Can you check if this happens in 1.0.0 when I post it tomorrow?

**Comment by imkingdavid** [comment] 2012-01-04 14:10
This is the same way submit_post() is used in the rest of phpBB, iirc. So I have no clue what the problem is.

EDIT: (Didn't mean to close this, just reopened it)

**Comment by erikfrerejean** [comment] 2012-01-04 16:26
Is the phpBB installation the latest?

**Comment by michaelcullum** [comment] 2012-01-04 16:30
I haven't had this error on 3.0.7, 3.0.7-PL1, 3.0.8, 3.0.9 and 3.0.10.

**Comment by erikfrerejean** [comment] 2012-01-04 16:31
No because _IIRC_ in 3.0.6 some changes where made to suppress/handle correctly these kind of errors.

**Closed as completed** 2012-01-10 00:11 UTC
Labels: Bug, Unreproducible
