### ISSUE TITLE
Manage Cats Page

### ISSUE THREAD

**Issue by michaelcullum** [phpBB-Blog/phpBB-Blog#73] opened 2012-02-07 19:11 UTC
https://gist.github.com/f5a7cc76d1571de841a1 explains the error and all related code (note the config.php db username and password have been changed)

**Comment by imkingdavid** [comment] 2012-02-27 21:02
Caused by #69 

/me slaps @erikfrerejean
Instead of removing the blog_constants.php include from the hook it should have been removed from blog.php.

The issue was
1) It couldn't find $table_prefix (fix: make it global)
2) It is already being included in blog.php (but not elsewhere) so it was redefining those things.

It's better to include whatever can be included in the hook rather than having multiple includes to it across files.

This will be fixed in my fork in a bit.

**Closed as completed** 2012-03-07 21:01 UTC
Labels: Bug, Blocker
