### ISSUE TITLE
New Data error

### ISSUE THREAD

**Issue by dragenx** [phpBB-Blog/phpBB-Blog#59] opened 2012-01-10 01:34 UTC
Just try instakking the mod on new install and got this error 

Inserting data in the phpbb_2blog_categories database table.
ERROR: Database table phpbb_2blog_categories does not exist.

phpBB Blog
PHP Version: 5.2.17
DBMS: MySQL 5.0.91-log
phpBB3 Version: 3.0.10

Inserting data in the phpbb_2blog_categories database table.
ERROR: Database table phpbb_2blog_categories does not exist.

**Comment by dragenx** [comment] 2012-01-10 01:38
General Error
SQL ERROR [ mysql4 ]

Table 'viperbase.BLOG_CATS_TABLE' doesn't exist [1146]

SQL

SELECT COUNT(cat_id) AS num_cats FROM BLOG_CATS_TABLE

BACKTRACE

FILE: [ROOT]/includes/db/mysql.php
LINE: 175
CALL: dbal->sql_error()

FILE: [ROOT]/includes/acp/acp_blog.php
LINE: 284
CALL: dbal_mysql->sql_query()

FILE: [ROOT]/includes/functions_module.php
LINE: 507
CALL: acp_blog->main()

FILE: [ROOT]/adm/index.php
LINE: 74
CALL: p_master->load_active()

**Comment by erikfrerejean** [comment] 2012-01-10 04:16
Can you please check your table prefix in `config.php` and post that back?

**Comment by dragenx** [comment] 2012-01-10 17:15
Loked at the config.php and this is the table prefix

$table_prefix = 'phpbb_2';

**Comment by erikfrerejean** [comment] 2012-01-10 17:34
Okay, thanks. I'll commit a definite fix for this later today. It's caused by mixing up hardcoded table names in the installer with dynamic table names in the blog itself.

**Comment by imkingdavid** [comment] 2012-01-10 22:09
IIRC, umil references to phpbb_ should be automatically changed if the prefix is different. But I guess updating the installer to use constants can't hurt.

**Comment by erikfrerejean** [comment] 2012-01-10 22:52
I don't know that, and rather not rely on that to begin with.

**Comment by imkingdavid** [comment] 2012-01-10 23:11
From: http://wiki.phpbb.com/Umil.table_add

"You may just use phpbb_ for the table prefix if you would like. UMIL correctly sets the table prefix to the board's default if you enter in phpbb_"

But whatever works. :)

**Comment by dragenx** [comment] 2012-01-10 23:26
My database is corrupt so I'm doing a clean install of the phpbb forum with new basebase hope it works this time I will post back on what happens

**Comment by dragenx** [comment] 2012-01-11 00:20
Did a clen install but went I click on the blog now getting this error

Parse error: syntax error, unexpected T_VARIABLE in D:\hosting\7757950\html\blog.php on line 107

Line: 107       $result = $db->sql_query_limit($sql, $sql_limit, $sql_start);

**Closed as completed** 2012-01-29 13:24 UTC
Labels: Bug, Blocker
